// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RuntimeCapture.proto
#ifndef GRPC_RuntimeCapture_2eproto__INCLUDED
#define GRPC_RuntimeCapture_2eproto__INCLUDED

#include "RuntimeCapture.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace SUU {
namespace Studio {

class RuntimeCapture final {
 public:
  static constexpr char const* service_full_name() {
    return "SUU.Studio.RuntimeCapture";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::SUU::Studio::SendImageRequest>> SendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::SUU::Studio::SendImageRequest>>(SendImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>> AsyncSendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>>(AsyncSendImageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>> PrepareAsyncSendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>>(PrepareAsyncSendImageRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::ClientWriteReactor< ::SUU::Studio::SendImageRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::SUU::Studio::SendImageRequest>* SendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>* AsyncSendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::SUU::Studio::SendImageRequest>* PrepareAsyncSendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::SUU::Studio::SendImageRequest>> SendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::SUU::Studio::SendImageRequest>>(SendImageRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>> AsyncSendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>>(AsyncSendImageRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>> PrepareAsyncSendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>>(PrepareAsyncSendImageRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendImage(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::ClientWriteReactor< ::SUU::Studio::SendImageRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::SUU::Studio::SendImageRequest>* SendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response) override;
    ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>* AsyncSendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::SUU::Studio::SendImageRequest>* PrepareAsyncSendImageRaw(::grpc::ClientContext* context, ::SUU::Studio::SendImageResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendImage(::grpc::ServerContext* context, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* reader, ::SUU::Studio::SendImageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* /*reader*/, ::SUU::Studio::SendImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::SUU::Studio::SendImageResponse, ::SUU::Studio::SendImageRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendImage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::SUU::Studio::SendImageRequest, ::SUU::Studio::SendImageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::SUU::Studio::SendImageResponse* response) { return this->SendImage(context, response); }));
    }
    ~WithCallbackMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* /*reader*/, ::SUU::Studio::SendImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::SUU::Studio::SendImageRequest>* SendImage(
      ::grpc::CallbackServerContext* /*context*/, ::SUU::Studio::SendImageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendImage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* /*reader*/, ::SUU::Studio::SendImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* /*reader*/, ::SUU::Studio::SendImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->SendImage(context, response); }));
    }
    ~WithRawCallbackMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::SUU::Studio::SendImageRequest>* /*reader*/, ::SUU::Studio::SendImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* SendImage(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace Studio
}  // namespace SUU


#endif  // GRPC_RuntimeCapture_2eproto__INCLUDED
