
name: Linux-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[Android]')
      && !contains(github.event.head_commit.message, '[Windows]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get install build-essential autoconf libtool pkg-config
          sudo apt update
          sudo apt install ninja-build
          sudo apt install libx11-dev
          
      - name: Install Cache
        uses: actions/cache@v2
        id: install-cache
        with:
          path: ./ThirdParty/Install/*
          key: install-cache

      - name: Install
        if: steps.install-cache.outputs.cache-hit != 'true'
        run: |
          chmod +x setup-linux.sh
          ./setup-linux.sh

      - name: Configure & Build
        working-directory: ./Linux/
        run: |
          chmod +x build-linux.sh
          ./build-linux.sh Release
          
      - name: Run tests
        working-directory: ./Linux/
        run: |
          cd build
          ./suu_runtime_test
          
        
