
name: Windows-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-2022
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[skip windows]')

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        id: setup_nuget

      - name: Install Cache
        uses: actions/cache@v2
        id: install-cache
        with:
          path: ./ThirdParty/Install/*
          key: install-cache-v3-${{ matrix.configuration }}

      - name: Install
        if: steps.install-cache.outputs.cache-hit != 'true'
        run: .\Setup.bat ${{ matrix.platform }} ${{ matrix.configuration }}
      
      - name: Restore the application
        working-directory: .\WindowsDesktop\VisualStudio2022\SUU-Runtime\
        run: nuget restore .\SUU-Runtime.sln

      - name: Run MSBuild
        id: run_msbuild
        working-directory: .\WindowsDesktop\VisualStudio2022\SUU-Runtime\
        run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} .\SUU-Runtime.sln
        
      - name: Run Test
        id: run_test
        working-directory: .\WindowsDesktop\VisualStudio2022\SUU-Runtime\output\SUU-Runtime-Test\${{ matrix.configuration }}\${{ matrix.platform }}\
        run: .\SUU-Runtime-Test.exe
  